AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for demo

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  DemoApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v2
      Cors:
        AllowMethods: "'DELETE,GET,HEAD,OPTIONS,POST,PUT'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  DemoFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./
      Handler: lambda.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          JWT_SECRET: teststring
      Events:
        Login:
          Type: Api
          Properties:
            Path: /login
            Method: post
            RestApiId: !Ref DemoApi
        Data:
          Type: Api
          Properties:
            Path: /data
            Method: get
            RestApiId: !Ref DemoApi

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Login:
    Value: !Sub "https://${DemoApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/login"
  Data:
    Value: !Sub "https://${DemoApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/data"

  DemoFunction:
    Description: "Demo Lambda Function ARN"
    Value: !GetAtt DemoFunction.Arn
  DemoFunctionIamRole:
    Description: "Implicit IAM Role created for Demo function"
    Value: !GetAtt DemoFunctionRole.Arn
